export const category = [
  {
    "id": "67fcc0db9424a73ca7f7f319",
    "name": "病理学检测",
    "number": "",
    "order": 10,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc0e69424a73ca7f7f31b",
    "name": "FISH",
    "number": "",
    "order": 20,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc0eb9424a73ca7f7f31d",
    "name": "化学发光法",
    "number": "",
    "order": 30,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc0f19424a73ca7f7f31f",
    "name": "均相酶免疫法",
    "number": "",
    "order": 40,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc0f89424a73ca7f7f321",
    "name": "酶联免疫法",
    "number": "",
    "order": 50,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc0fe9424a73ca7f7f323",
    "name": "免疫法",
    "number": "",
    "order": 60,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc1039424a73ca7f7f325",
    "name": "NGS",
    "number": "",
    "order": 70,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc1089424a73ca7f7f327",
    "name": "生化法",
    "number": "",
    "order": 80,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc1139424a73ca7f7f329",
    "name": "数字PCR",
    "number": "",
    "order": 90,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc11a9424a73ca7f7f32b",
    "name": "形态学",
    "number": "",
    "order": 100,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc11f9424a73ca7f7f32d",
    "name": "一代测序",
    "number": "",
    "order": 110,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc1239424a73ca7f7f32f",
    "name": "荧光PCR",
    "number": "",
    "order": 120,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc1299424a73ca7f7f331",
    "name": "原子吸收法",
    "number": "",
    "order": 130,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc1309424a73ca7f7f333",
    "name": "质谱法",
    "number": "",
    "order": 140,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "68005d4e5623002885c4848e",
    "name": "套餐",
    "number": "",
    "order": 999,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "SALE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  }
]


export const disease = [
  {
    "id": "67fcc2999424a73ca7f7f337",
    "name": "常规检测",
    "number": "",
    "order": 20,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc29e9424a73ca7f7f339",
    "name": "妇产类检测",
    "number": "",
    "order": 30,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc2a39424a73ca7f7f33b",
    "name": "感染类检测",
    "number": "",
    "order": 40,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc2a89424a73ca7f7f33d",
    "name": "实体瘤检测",
    "number": "",
    "order": 50,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc2ad9424a73ca7f7f33f",
    "name": "血液肿瘤检测",
    "number": "",
    "order": 60,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc2b39424a73ca7f7f341",
    "name": "药物基因检测",
    "number": "",
    "order": 70,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc2bb9424a73ca7f7f343",
    "name": "药物浓度检测",
    "number": "",
    "order": 80,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "67fcc2c09424a73ca7f7f345",
    "name": "肿瘤早筛检测",
    "number": "",
    "order": 90,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  },
  {
    "id": "68005d155623002885c4848c",
    "name": "套餐",
    "number": "",
    "order": 999,
    "parentId": null,
    "ancestors": [],
    "nodeType": null,
    "treeKey": "DISEASE_CATEGORY_TREE",
    "count": null,
    "cacheData": {},
    "children": []
  }
]